/*
 * API de Básculas
 *
 * API de administración de Básculas
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using AutoMapper;
using EVO_BusinessLogic;
using EVO_BusinessObjects;
using EVO_BusinessObjects.Exceptions;
using EVO_WebApi.Attributes;
using EVO_WebApi.Models.BasculasApi;
using EVO_WebApi.Resources;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NLog;
using Swashbuckle.AspNetCore.Annotations;
using System.Collections.Generic;

namespace EVO_WebApi.Controllers
{

    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class BasculasApiController : ControllerBase
    {
        #region Campos Privados
        private static readonly Logger logger = LogManager.GetCurrentClassLogger();
        private IMapper mapper;
        #endregion

        #region Métodos Públicos
        /// <summary>
        /// Obtiene todos los tipos de básculas
        /// </summary>
        /// <response code="200">Operación realizada con éxito</response>
        [HttpGet]
        [Route("/api/tipobasculas/")]
        [ValidateModelState]
        [SwaggerOperation("ObtenerTipoBasculas")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<TipoBasculaResponse>), description: "Operación realizada con éxito")]
        public virtual IActionResult ObtenerTipoBasculas()
        {
            logger.Info($"Entró al método ObtenerTipoBasculas en Api Básculas");

            try
            {
                BlBascula blBascula = new BlBascula();

                List<BOTipoBascula> tiposBascula = blBascula.ObtenerTipoBasculas();

                List<TipoBasculaResponse> tipoBasculaResponse = this.mapper.Map<List<BOTipoBascula>, List<TipoBasculaResponse>>(tiposBascula);

                return Ok(tipoBasculaResponse);
            }
            catch (EVOException e)
            {
                return StatusCode(StatusCodes.Status400BadRequest, e.Message);
            }
            catch
            {
                return StatusCode(StatusCodes.Status500InternalServerError, errores.errGeneral);
            }
        } 
        #endregion

        #region Contructores
        /// <summary>
        /// 
        /// </summary>
        /// <param name="mapper"></param>
        public BasculasApiController(IMapper mapper)
        {
            this.mapper = mapper;
        }
        #endregion

    }
}
