/*
 * API de Pedidos
 *
 * API de administración de Pedidos 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Text;

namespace EVO_WebApi.Models.PedidosApi
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ObtenerPedidosCompraResponseRegistros : IEquatable<ObtenerPedidosCompraResponseRegistros>
    {
        /// <summary>
        /// Id del pedido
        /// </summary>
        /// <value>Id del pedido</value>
        [DataMember(Name = "pedidoId")]
        public int? PedidoId { get; set; }

        /// <summary>
        /// Número del pedido
        /// </summary>
        /// <value>Número del pedido</value>
        [DataMember(Name = "numeroPedido")]
        public string NumeroPedido { get; set; }

        /// <summary>
        /// Fecha de solicitud del pedido
        /// </summary>
        /// <value>Fecha de solicitud del pedido</value>
        [DataMember(Name = "fechaSolicitud")]
        public string FechaSolicitud { get; set; }

        /// <summary>
        /// Fecha limite de entrega sugerida del pedido
        /// </summary>
        /// <value>Fecha limite de entrega sugerida del pedido</value>
        [DataMember(Name = "fechaLimiteSugerida")]
        public string FechaLimiteSugerida { get; set; }

        /// <summary>
        /// Estado el pedido
        /// </summary>
        /// <value>Estado el pedido</value>
        [DataMember(Name = "estado")]
        public string Estado { get; set; }

        /// <summary>
        /// Nombre del cliente
        /// </summary>
        /// <value>Nombre del cliente</value>
        [DataMember(Name = "cliente")]
        public string Cliente { get; set; }

        /// <summary>
        /// Días que faltan para la entrega del pedido
        /// </summary>
        /// <value>Días que faltan para la entrega del pedido</value>
        [DataMember(Name = "diasEntrega")]
        public string DiasEntrega { get; set; }

        /// <summary>
        /// Indica si se puede editar el registro
        /// </summary>
        /// <value>True</value>
        [DataMember(Name = "editarPedido")]
        public bool EditarPedido { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ObtenerPedidosCompraResponseRegistros {\n");
            sb.Append("  PedidoId: ").Append(PedidoId).Append("\n");
            sb.Append("  NumeroPedido: ").Append(NumeroPedido).Append("\n");
            sb.Append("  FechaSolicitud: ").Append(FechaSolicitud).Append("\n");
            sb.Append("  FechaLimiteSugerida: ").Append(FechaLimiteSugerida).Append("\n");
            sb.Append("  Estado: ").Append(Estado).Append("\n");
            sb.Append("  Cliente: ").Append(Cliente).Append("\n");
            sb.Append("  DiasEntrega: ").Append(DiasEntrega).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ObtenerPedidosCompraResponseRegistros)obj);
        }

        /// <summary>
        /// Returns true if ObtenerPedidosCompraResponseRegistros instances are equal
        /// </summary>
        /// <param name="other">Instance of ObtenerPedidosCompraResponseRegistros to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ObtenerPedidosCompraResponseRegistros other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PedidoId == other.PedidoId ||
                    PedidoId != null &&
                    PedidoId.Equals(other.PedidoId)
                ) &&
                (
                    NumeroPedido == other.NumeroPedido ||
                    NumeroPedido != null &&
                    NumeroPedido.Equals(other.NumeroPedido)
                ) &&
                (
                    FechaSolicitud == other.FechaSolicitud ||
                    FechaSolicitud != null &&
                    FechaSolicitud.Equals(other.FechaSolicitud)
                ) &&
                (
                    FechaLimiteSugerida == other.FechaLimiteSugerida ||
                    FechaLimiteSugerida != null &&
                    FechaLimiteSugerida.Equals(other.FechaLimiteSugerida)
                ) &&
                (
                    Estado == other.Estado ||
                    Estado != null &&
                    Estado.Equals(other.Estado)
                ) &&
                (
                    Cliente == other.Cliente ||
                    Cliente != null &&
                    Cliente.Equals(other.Cliente)
                ) &&
                (
                    DiasEntrega == other.DiasEntrega ||
                    DiasEntrega != null &&
                    DiasEntrega.Equals(other.DiasEntrega)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (PedidoId != null)
                    hashCode = hashCode * 59 + PedidoId.GetHashCode();
                if (NumeroPedido != null)
                    hashCode = hashCode * 59 + NumeroPedido.GetHashCode();
                if (FechaSolicitud != null)
                    hashCode = hashCode * 59 + FechaSolicitud.GetHashCode();
                if (FechaLimiteSugerida != null)
                    hashCode = hashCode * 59 + FechaLimiteSugerida.GetHashCode();
                if (Estado != null)
                    hashCode = hashCode * 59 + Estado.GetHashCode();
                if (Cliente != null)
                    hashCode = hashCode * 59 + Cliente.GetHashCode();
                if (DiasEntrega != null)
                    hashCode = hashCode * 59 + DiasEntrega.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ObtenerPedidosCompraResponseRegistros left, ObtenerPedidosCompraResponseRegistros right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ObtenerPedidosCompraResponseRegistros left, ObtenerPedidosCompraResponseRegistros right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
