/*
 * API de Artículos
 *
 * API de administración de Articulos 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jegiraldo@porcicarnes.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EVO_PB.Models.ArticlesApi
{
    /// <summary>
    /// Indica los parámetros de búsqueda
    /// </summary>
    [DataContract]
    public partial class BuscarArticuloRequest : IEquatable<BuscarArticuloRequest>
    {
        /// <summary>
        /// Nombre del artículo
        /// </summary>
        /// <value>Nombre del artículo</value>
        [DataMember(Name = "Nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Código del artículo
        /// </summary>
        /// <value>Código del artículo</value>
        [DataMember(Name = "Codigo")]
        public string Codigo { get; set; }

        /// <summary>
        /// Código de la bodega
        /// </summary>
        /// <value>Código de la bodega</value>
        [Required]
        [DataMember(Name = "CodigoBodega")]
        public string CodigoBodega { get; set; }

        /// <summary>
        /// Prefijo de los artículos , la planta tiene por ejemplo PB-PT y los artículos tienen PT-2456
        /// </summary>
        /// <value>PT-</value>       
        [DataMember(Name = "PrefijoCodigoArticulo")]
        public string PrefijoCodigoArticulo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BuscarArticuloRequest {\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Codigo: ").Append(Codigo).Append("\n");
            sb.Append("  CodigoBodega: ").Append(CodigoBodega).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BuscarArticuloRequest)obj);
        }

        /// <summary>
        /// Returns true if BuscarArticuloRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of BuscarArticuloRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BuscarArticuloRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                ) &&
                (
                    Codigo == other.Codigo ||
                    Codigo != null &&
                    Codigo.Equals(other.Codigo)
                ) &&
                (
                    CodigoBodega == other.CodigoBodega ||
                    CodigoBodega != null &&
                    CodigoBodega.Equals(other.CodigoBodega)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                if (Codigo != null)
                    hashCode = hashCode * 59 + Codigo.GetHashCode();
                if (CodigoBodega != null)
                    hashCode = hashCode * 59 + CodigoBodega.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(BuscarArticuloRequest left, BuscarArticuloRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BuscarArticuloRequest left, BuscarArticuloRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
