//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVO_PB.Resources.Dictionaries {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DictMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVO_PB.Resources.Dictionaries.DictMessages", typeof(DictMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo eliminado correctamente.
        /// </summary>
        internal static string ArticuloEliminadoCorrectamente {
            get {
                return ResourceManager.GetString("ArticuloEliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos eliminados correctamente.
        /// </summary>
        internal static string ArticulosEliminadosCorrectamente {
            get {
                return ResourceManager.GetString("ArticulosEliminadosCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro qué desea enviar el pedido?.
        /// </summary>
        internal static string ConfirmarEnviarSolicitudPedidoAComercial {
            get {
                return ResourceManager.GetString("ConfirmarEnviarSolicitudPedidoAComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro qué desea guardar el pedido?.
        /// </summary>
        internal static string ConfirmarGuadarSolicitudPedido {
            get {
                return ResourceManager.GetString("ConfirmarGuadarSolicitudPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro qué desea guardar este pesaje?.
        /// </summary>
        internal static string ConfirmarPesajeBascula {
            get {
                return ResourceManager.GetString("ConfirmarPesajeBascula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el artículo de la solicitud ?.
        /// </summary>
        internal static string EliminarArticuloPedido {
            get {
                return ResourceManager.GetString("EliminarArticuloPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cambio de planta eliminará los artículos. ¿Está seguro?.
        /// </summary>
        internal static string EliminarArticulosCambioPlanta {
            get {
                return ResourceManager.GetString("EliminarArticulosCambioPlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar los artículos de la solicitud?.
        /// </summary>
        internal static string EliminarArticulosPedido {
            get {
                return ResourceManager.GetString("EliminarArticulosPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El artículo {0} con código {1} está dos veces.
        /// </summary>
        internal static string ErrMasDosArticulos {
            get {
                return ResourceManager.GetString("ErrMasDosArticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos iguales con el mismo estado .
        /// </summary>
        internal static string ErrorArticuloOrdenMismoEstado {
            get {
                return ResourceManager.GetString("ErrorArticuloOrdenMismoEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe informar la cántidad del artículo.
        /// </summary>
        internal static string ErrorCantidadArticulo {
            get {
                return ResourceManager.GetString("ErrorCantidadArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe informar el estado del artículo.
        /// </summary>
        internal static string ErrorEstadoArticulo {
            get {
                return ResourceManager.GetString("ErrorEstadoArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de entrega es necesaria.
        /// </summary>
        internal static string ErrorFechaEntregaSolicitudPedidoAbierto {
            get {
                return ResourceManager.GetString("ErrorFechaEntregaSolicitudPedidoAbierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de pedido no puede mayor a la fecha actual.
        /// </summary>
        internal static string ErrorFechaPedidoMayorActual {
            get {
                return ResourceManager.GetString("ErrorFechaPedidoMayorActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algo ocurrio en el sistema.
        /// </summary>
        internal static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualmente existe una solicitud.
        /// </summary>
        internal static string ErrorOrderErased {
            get {
                return ResourceManager.GetString("ErrorOrderErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud debe tener como mínimo un artículo.
        /// </summary>
        internal static string ErrorPedidoSinArticulos {
            get {
                return ResourceManager.GetString("ErrorPedidoSinArticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una planta.
        /// </summary>
        internal static string ErrorSeleccionarPlanta {
            get {
                return ResourceManager.GetString("ErrorSeleccionarPlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha seleccionado una planta.
        /// </summary>
        internal static string NoArticulosPlanta {
            get {
                return ResourceManager.GetString("NoArticulosPlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La bodega no ha sido seleccionada.
        /// </summary>
        internal static string NoSeleccionadoBodega {
            get {
                return ResourceManager.GetString("NoSeleccionadoBodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un artículo.
        /// </summary>
        internal static string NoSeleccionadoDetalleArticulo {
            get {
                return ResourceManager.GetString("NoSeleccionadoDetalleArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de báscula no ha sido seleccionado.
        /// </summary>
        internal static string NoSeleccionadoTipoBascula {
            get {
                return ResourceManager.GetString("NoSeleccionadoTipoBascula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso del artículo no es valido.
        /// </summary>
        internal static string PesoArticuloNoValido {
            get {
                return ResourceManager.GetString("PesoArticuloNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso de la báscula no es valido.
        /// </summary>
        internal static string PesoBasculaNoValido {
            get {
                return ResourceManager.GetString("PesoBasculaNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso del contenedor no es valido.
        /// </summary>
        internal static string PesoContenedoresNoValido {
            get {
                return ResourceManager.GetString("PesoContenedoresNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud registrado correctamente.
        /// </summary>
        internal static string RegistrarSolicitudPedidoBorrador {
            get {
                return ResourceManager.GetString("RegistrarSolicitudPedidoBorrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud enviada correctamente.
        /// </summary>
        internal static string RegistrarSolicitudPedidoDefinitivo {
            get {
                return ResourceManager.GetString("RegistrarSolicitudPedidoDefinitivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existen borradores para cada planta.
        /// </summary>
        internal static string SolicitudesBorradores {
            get {
                return ResourceManager.GetString("SolicitudesBorradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correcto.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peligro.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
