/*
 * API de Autenticación de Usuario
 *
 * API de administración de autenticación de usuario
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Text;

namespace EVO_WebApi.Models.AutenticarApi
{
    /// <summary>
    /// Criterios por los que se filtrará la consulta
    /// </summary>
    [DataContract]
    public partial class FiltrarSesionRequestFiltro : IEquatable<FiltrarSesionRequestFiltro>
    {
        /// <summary>
        /// Filtro por sesion Id
        /// </summary>
        /// <value>Filtro por sesion Id</value>
        [DataMember(Name = "sesionId")]
        public string SesionId { get; set; }

        /// <summary>
        /// Filtro por IP
        /// </summary>
        /// <value>Filtro por IP</value>
        [DataMember(Name = "ip")]
        public string Ip { get; set; }

        /// <summary>
        /// Filtro por token
        /// </summary>
        /// <value>Filtro por token</value>
        [DataMember(Name = "token")]
        public string Token { get; set; }

        /// <summary>
        /// Filtro por usuario
        /// </summary>
        /// <value>Filtro por usuario</value>
        [DataMember(Name = "usuario")]
        public string Usuario { get; set; }

        /// <summary>
        /// Filtro por fecha de inicio
        /// </summary>
        /// <value>Filtro por fecha de inicio</value>
        [DataMember(Name = "fecheInicio")]
        public string FecheInicio { get; set; }

        /// <summary>
        /// Filtro por fecha de expiración
        /// </summary>
        /// <value>Filtro por fecha de expiración</value>
        [DataMember(Name = "fecheExpiracion")]
        public string FecheExpiracion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FiltrarSesionRequestFiltro {\n");
            sb.Append("  SesionId: ").Append(SesionId).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  Usuario: ").Append(Usuario).Append("\n");
            sb.Append("  FecheInicio: ").Append(FecheInicio).Append("\n");
            sb.Append("  FecheExpiracion: ").Append(FecheExpiracion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FiltrarSesionRequestFiltro)obj);
        }

        /// <summary>
        /// Returns true if FiltrarSesionRequestFiltro instances are equal
        /// </summary>
        /// <param name="other">Instance of FiltrarSesionRequestFiltro to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FiltrarSesionRequestFiltro other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    SesionId == other.SesionId ||
                    SesionId != null &&
                    SesionId.Equals(other.SesionId)
                ) &&
                (
                    Ip == other.Ip ||
                    Ip != null &&
                    Ip.Equals(other.Ip)
                ) &&
                (
                    Token == other.Token ||
                    Token != null &&
                    Token.Equals(other.Token)
                ) &&
                (
                    Usuario == other.Usuario ||
                    Usuario != null &&
                    Usuario.Equals(other.Usuario)
                ) &&
                (
                    FecheInicio == other.FecheInicio ||
                    FecheInicio != null &&
                    FecheInicio.Equals(other.FecheInicio)
                ) &&
                (
                    FecheExpiracion == other.FecheExpiracion ||
                    FecheExpiracion != null &&
                    FecheExpiracion.Equals(other.FecheExpiracion)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (SesionId != null)
                    hashCode = hashCode * 59 + SesionId.GetHashCode();
                if (Ip != null)
                    hashCode = hashCode * 59 + Ip.GetHashCode();
                if (Token != null)
                    hashCode = hashCode * 59 + Token.GetHashCode();
                if (Usuario != null)
                    hashCode = hashCode * 59 + Usuario.GetHashCode();
                if (FecheInicio != null)
                    hashCode = hashCode * 59 + FecheInicio.GetHashCode();
                if (FecheExpiracion != null)
                    hashCode = hashCode * 59 + FecheExpiracion.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(FiltrarSesionRequestFiltro left, FiltrarSesionRequestFiltro right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FiltrarSesionRequestFiltro left, FiltrarSesionRequestFiltro right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
