/*
 * API de Documentos
 *
 * API de administración de Documentos 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Text;

namespace EVO_WebApi.Models.DocumentosApi
{
    /// <summary>
    /// Representa la respuesta de un documento
    /// </summary>
    [DataContract]
    public partial class DocumentoResponse : IEquatable<DocumentoResponse>
    {
        /// <summary>
        /// Id del documento
        /// </summary>
        /// <value>Id del documento</value>
        [DataMember(Name = "documentoId")]
        public int DocumentoId { get; set; }

        /// <summary>
        /// Nombre del documento
        /// </summary>
        /// <value>Nombre del documento</value>
        [DataMember(Name = "documento")]
        public string Documento { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentoResponse {\n");
            sb.Append("  DocumentoId: ").Append(DocumentoId).Append("\n");
            sb.Append("  Documento: ").Append(Documento).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DocumentoResponse)obj);
        }

        /// <summary>
        /// Returns true if DocumentoResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of DocumentoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentoResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    DocumentoId == other.DocumentoId ||
                    DocumentoId != null &&
                    DocumentoId.Equals(other.DocumentoId)
                ) &&
                (
                    Documento == other.Documento ||
                    Documento != null &&
                    Documento.Equals(other.Documento)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (DocumentoId != null)
                    hashCode = hashCode * 59 + DocumentoId.GetHashCode();
                if (Documento != null)
                    hashCode = hashCode * 59 + Documento.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(DocumentoResponse left, DocumentoResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DocumentoResponse left, DocumentoResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
