/*
 * API de Vehiculos
 *
 * API de administración de Vehiculos 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models.VehiculosApi
{ 
    /// <summary>
    /// Indica un muelle
    /// </summary>
    [DataContract]
    public partial class MuelleResponse : IEquatable<MuelleResponse>
    { 
        /// <summary>
        /// Id del muelle
        /// </summary>
        /// <value>Id del muelle</value>
        [Required]
        [DataMember(Name="MuelleId")]
        public int MuelleId { get; set; }

        /// <summary>
        /// Valor del muelle
        /// </summary>
        /// <value>Valor del muelle</value>
        [Required]
        [DataMember(Name="Muelle")]
        public string Muelle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MuelleResponse {\n");
            sb.Append("  MuelleId: ").Append(MuelleId).Append("\n");
            sb.Append("  Muelle: ").Append(Muelle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MuelleResponse)obj);
        }

        /// <summary>
        /// Returns true if MuelleResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of MuelleResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MuelleResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MuelleId == other.MuelleId ||
                    MuelleId != null &&
                    MuelleId.Equals(other.MuelleId)
                ) && 
                (
                    Muelle == other.Muelle ||
                    Muelle != null &&
                    Muelle.Equals(other.Muelle)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MuelleId != null)
                    hashCode = hashCode * 59 + MuelleId.GetHashCode();
                    if (Muelle != null)
                    hashCode = hashCode * 59 + Muelle.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MuelleResponse left, MuelleResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MuelleResponse left, MuelleResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
