/*
 * API de Pedidos
 *
 * API de administración de Pedidos 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models.PedidosApi
{
    /// <summary>
    /// Crea o actualiza una distribución
    /// </summary>
    [DataContract]
    public partial class AsignarDistribucionRequest : IEquatable<AsignarDistribucionRequest>
    {
        /// <summary>
        /// Id del vehiculo
        /// </summary>
        /// <value>Id del vehiculo</value>
        [Required]
        [DataMember(Name = "vehiculoId")]
        public int VehiculoId { get; set; }

        /// <summary>
        /// Id del conductor
        /// </summary>
        /// <value>Id del conductor</value>
        [Required]
        [DataMember(Name = "conductorId")]
        public int ConductorId { get; set; }

        /// <summary>
        /// Id del muelle
        /// </summary>
        /// <value>Id del muelle</value>
        [Required]
        [DataMember(Name = "muelleId")]
        public int MuelleId { get; set; }

        /// <summary>
        /// Id del conductor auxiliar
        /// </summary>
        /// <value>Id del conductor auxiliar</value>
        [Required]
        [DataMember(Name = "auxiliarId")]
        public int AuxiliarId { get; set; }

        /// <summary>
        /// Ids de las entregas asociadas al viaje
        /// </summary>
        /// <value>Ids de las entregas asociadas al viaje</value>
        [Required]
        [DataMember(Name = "entregasIds")]
        public List<int> EntregasIds { get; set; }

        /// <summary>
        /// Identifica si es o no un nuevo viaje
        /// </summary>
        /// <value>Identifica si es o no un nuevo viaje</value>
        [Required]
        [DataMember(Name = "nuevoViaje")]
        public bool? NuevoViaje { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AsignarDistribucionRequest {\n");
            sb.Append("  VehiculoId: ").Append(VehiculoId).Append("\n");
            sb.Append("  ConductorId: ").Append(ConductorId).Append("\n");
            sb.Append("  MuelleId: ").Append(MuelleId).Append("\n");
            sb.Append("  AuxiliarId: ").Append(AuxiliarId).Append("\n");
            sb.Append("  EntregasIds: ").Append(EntregasIds).Append("\n");
            sb.Append("  NuevoViaje: ").Append(NuevoViaje).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AsignarDistribucionRequest)obj);
        }

        /// <summary>
        /// Returns true if AsignarDistribucionRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AsignarDistribucionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AsignarDistribucionRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VehiculoId == other.VehiculoId ||
                    VehiculoId != null &&
                    VehiculoId.Equals(other.VehiculoId)
                ) &&
                (
                    ConductorId == other.ConductorId ||
                    ConductorId != null &&
                    ConductorId.Equals(other.ConductorId)
                ) &&
                (
                    MuelleId == other.MuelleId ||
                    MuelleId != null &&
                    MuelleId.Equals(other.MuelleId)
                ) &&
                (
                    AuxiliarId == other.AuxiliarId ||
                    AuxiliarId != null &&
                    AuxiliarId.Equals(other.AuxiliarId)
                ) &&
                (
                    EntregasIds == other.EntregasIds ||
                    EntregasIds != null &&
                    EntregasIds.SequenceEqual(other.EntregasIds)
                ) &&
                (
                    NuevoViaje == other.NuevoViaje ||
                    NuevoViaje != null &&
                    NuevoViaje.Equals(other.NuevoViaje)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (VehiculoId != null)
                    hashCode = hashCode * 59 + VehiculoId.GetHashCode();
                if (ConductorId != null)
                    hashCode = hashCode * 59 + ConductorId.GetHashCode();
                if (MuelleId != null)
                    hashCode = hashCode * 59 + MuelleId.GetHashCode();
                if (AuxiliarId != null)
                    hashCode = hashCode * 59 + AuxiliarId.GetHashCode();
                if (EntregasIds != null)
                    hashCode = hashCode * 59 + EntregasIds.GetHashCode();
                if (NuevoViaje != null)
                    hashCode = hashCode * 59 + NuevoViaje.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(AsignarDistribucionRequest left, AsignarDistribucionRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AsignarDistribucionRequest left, AsignarDistribucionRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
