/*
 * API de Pedidos
 *
 * API de administración de Pedidos 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;

namespace EVO_WebApi.Models.PedidosApi
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EntregaResponseDetalles
    {
        /// <summary>
        /// Id del detalle de la entrega
        /// </summary>
        /// <value>Id del detalle de la entrega</value>
        [DataMember(Name = "detalleEntregaId")]
        public int DetalleEntregaId { get; set; }

        /// <summary>
        /// ID del estado del Artículo
        /// </summary>
        /// <value>ID del estado del Artículo</value>
        [DataMember(Name = "idEstadoArticulo")]
        public int IdEstadoArticulo { get; set; }

        /// <summary>
        /// Código Artículo
        /// </summary>
        /// <value>Código Artículo</value>
        [DataMember(Name = "codigo")]
        public string Codigo { get; set; }

        /// <summary>
        /// Nombre Artículo
        /// </summary>
        /// <value>Nombre Artículo</value>
        [DataMember(Name = "nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Cantidad a enviar
        /// </summary>
        /// <value>Cantidad a enviar</value>
        [DataMember(Name = "cantidadAprobada")]
        public string CantidadAprobada { get; set; }

        /// <summary>
        /// Cantidad Aprobada del articulo en comercial
        /// </summary>
        /// <value>Cantidad a enviar</value>   
        /// 
        //TODO: Pendiente de agregar a swagger
        [DataMember(Name = "cantidadPendiente")]
        public string CantidadPendiente { get; set; }

        /// <summary>
        /// Cantidad Aprobada del articulo en comercial
        /// </summary>
        /// <value>Cantidad a enviar</value>   
        /// 
        //TODO: Pendiente de agregar a swagger
        [DataMember(Name = "cantidadEntrega")]
        public string CantidadEntrega { get; set; }

        /// <summary>
        /// Observación
        /// </summary>       
        [DataMember(Name = "observacion")]
        public string Observacion { get; set; }

    }
}
