/*
 * API de administración de Facturación
 *
 * API de administración de facturación 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jusuga@digitalcg.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Text;

namespace EVO_WebApi.Models.FacturacionApi
{
    /// <summary>
    /// Representa una banco
    /// </summary>
    [DataContract]
    public partial class BancoResponse : IEquatable<BancoResponse>
    {
        /// <summary>
        /// Indica el id
        /// </summary>
        /// <value>I1</value>
        [DataMember(Name = "bancoId")]
        public int BancoId { get; set; }

        /// <summary>
        /// Indica el NIT
        /// </summary>
        /// <value>800037000-5</value>
        [DataMember(Name = "nit")]
        public string NIT { get; set; }

        /// <summary>
        /// Indica el nombre
        /// </summary>
        /// <value>Banco123</value>
        [DataMember(Name = "nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BancoResponse {\n");
            sb.Append("  BancoId: ").Append(BancoId).Append("\n");
            sb.Append("  NIT: ").Append(NIT).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BancoResponse)obj);
        }

        /// <summary>
        /// Returns true if BancoResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of BancoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BancoResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    BancoId == other.BancoId ||
                    BancoId != null &&
                    BancoId.Equals(other.BancoId)
                ) &&
                (
                    NIT == other.NIT ||
                    NIT != null &&
                    NIT.Equals(other.NIT)
                )
                &&
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (BancoId != null)
                    hashCode = hashCode * 59 + BancoId.GetHashCode();
                if (NIT != null)
                    hashCode = hashCode * 59 + NIT.GetHashCode();
                if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(BancoResponse left, BancoResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BancoResponse left, BancoResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
