/*
 * API de Artículos
 *
 * API de administración de Articulos 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jegiraldo@porcicarnes.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EVO_PV.Models.ArticlesApi
{
    /// <summary>
    /// Indica un estado del artículo
    /// </summary>
    [DataContract]
    public partial class EstadoArticuloResponse : IEquatable<EstadoArticuloResponse>
    {
        /// <summary>
        /// Id del estado del artículo
        /// </summary>
        /// <value>Id del estado del artículo</value>
        [Required]
        [DataMember(Name = "EstadoArticuloId")]
        public int EstadoArticuloId { get; set; }

        /// <summary>
        /// Estado del artículo
        /// </summary>
        /// <value>Estado del artículo</value>
        [Required]
        [DataMember(Name = "Nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EstadoArticuloResponse {\n");
            sb.Append("  EstadoArticuloId: ").Append(EstadoArticuloId).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EstadoArticuloResponse)obj);
        }

        /// <summary>
        /// Returns true if EstadoArticuloResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of EstadoArticuloResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EstadoArticuloResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    EstadoArticuloId == other.EstadoArticuloId ||
                    EstadoArticuloId != null &&
                    EstadoArticuloId.Equals(other.EstadoArticuloId)
                ) &&
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (EstadoArticuloId != null)
                    hashCode = hashCode * 59 + EstadoArticuloId.GetHashCode();
                if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(EstadoArticuloResponse left, EstadoArticuloResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EstadoArticuloResponse left, EstadoArticuloResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
