openapi: 3.0.0
servers:
  - description: EVO - API de Entregas
    url: https://evo/api
info:
  description: |
   API de administración de Entregas
  version: "1.0.0"
  title: API de Entregas
  termsOfService: 'https://www.porcicarnes.com/'
  contact:
    email: jusuga@digitalcg.com.co
tags:
  - name: Entregas
    description: Gestión de Entregas
paths:
  /entregas/pedidoid:
   get:
      tags:
       - Entregas
      summary: Obtiene las entregas por pedidoId 
      operationId: obtenerEntregasxPedidoId
      parameters:
        - name : pedidoId
          in: query
          description: Indica el id del pedido
          required: true
          schema:
           type: integer
      responses:
        '200':
          description: Operación realizada con éxito
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/EntregaResponse'
  /entregas/articulos/eliminar:
   post:
      tags:
       - Entregas
      summary: edita un artículo asociado a una entrega en el módulo de distribución
      operationId: eliminarArticuloDistribucion
      requestBody:
          $ref: '#/components/requestBodies/EliminarArticuloDistribucionRequest'
      responses:
        '200':
          description: Operación realizada con éxito
  /entregas/articulos/pendientes:
   get:
      tags:
       - Entregas
      summary: Obtiene los artículos que no están en esta entrega
      operationId: obtenerArticulosPendientes
      parameters:
        - name : entregaId
          in: query
          description: Indica el id de la entrega
          required: true
          schema:
           type: integer
      responses:
        '200':
          description: Operación realizada con éxito
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/ArticuloPendienteResponse'
  /entregas/enrutamiento:
   get:
      tags:
        - Entregas
      summary: Obtiene los registros de las entregas de los pedidos en enrutamiento
      operationId: obtenerTodosEntregasEnrutamiento
      parameters:
        - name: desde
          in: query
          description: Indica el número de registro desde el cuál se deben obtener los registros
          required: true
          schema:
            type: integer
        - name: hasta
          in: query
          description: Indica el número de registro hasta el cuál se deben obtener los registros
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Operación realizada con éxito
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ObtenerTodosEntregasDistribucionResponse'  
components:
  schemas:
    EntregaResponse:
      type: object
      description: Representa una entrega de un pedido
      properties:
        EntregaId:
          type: integer
          example: "1"
          description: Id de la entrega 
        NumeroEntrega:
          type: string
          example: "1/4"
          description: Número de la entrega
        FechaHoraEntrega:
          type: string         
          example: "12/12/2020 02:03:59"
          description: Fecha y hora de la entrega
        FinalizadoRecepcion:
          type: boolean         
          example: true
          description: Indica si ya finalizó el pesaje en recepción 
    EliminarArticuloDistribucionRequest:
      type: object
      description: Objeto que hace la petición para eliminar/editar una articulo en entrega dentro del modelo de distribución
      properties:
        MotivoId:
          type: integer
          example: "1"
          description: Id del motivo entrega 
        DetalleEntregaId:
          type: integer
          example: "1"
          description: Id del detalle de la entrega 
    ArticuloPendienteResponse:
      type: object
      description: Obtiene los artículos pendientes que no están en la entrega
      properties:
        IdEstadoArticulo:
          type: integer
          example: "1"
          description: ID del estado del Artículo
        codigo:
          type: string
          example: 'PT-1485'
          description: Código del artículo
        nombre:
          type: string
          example: 'Cabeza de cerdo'
          description: Nombre del artículo
        cantidadAprobada:
          type: string
          example: '1000000'
          description: Cantidad aprobada
        cantidadPendiente:
          type: string
          example: '123'
          description: Cantidad pendiente
    ObtenerTodosEntregasDistribucionResponse:
      type: object
      description: Resultado general de consulta
      properties:
        numeroTotalRegistros:
          type: integer
          example: 37567
          description: Número total de registros que posee la consulta
        tamanhoPaginacion:
          type: integer
          example: 50
          description: Número de registros a mostrar por página
        registros:
          type: array
          description: Lista de registros de entregas
          items:
            type: object
            properties:
              entregaId:
                type: integer
                example: 1
                description: Id de entrega            
              cliente:
                type: string
                example: "Punto de venta Prado"
                description: Nombre del cliente
              codigoPedido:
                type: string
                example: "PV-01"
                description: Código del pedido
              numeroEntrga:
                type: string
                example: "1"
                description: Número de la entrega
              fechaEntrega:
                type: string
                example: "30/08/2019"
                description: Fecha de la entrega 
              horaEntrega:
                type: string
                example: "12:45"
                description: Horaentrega
              peso:
                type: string
                example: "233.567 kg"
                description: Peso de los artículos de las entregas
              zona:
               type: string
               example: "Norte 1"
               description: Indica la zona del punto de venta o cliente externo
  requestBodies:
   EliminarArticuloDistribucionRequest:
      content:
        application/json:
          schema:
              $ref: '#/components/schemas/EliminarArticuloDistribucionRequest'
      description: Referencia del body al modelo EliminarArticuloDistribucionRequest
      required: true